# Generated by Django 2.1.2 on 2018-11-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
